FROM bitnami/laravel:latest

# Instala Git e SSH
USER root
RUN apt-get update && apt-get install -y \
    git \
    openssh-server \
    nano \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Configura SSH
RUN mkdir /var/run/sshd
RUN echo 'root:docker123' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22

# Script de inicialização
COPY init-git.sh /init-git.sh
RUN chmod +x /init-git.sh

WORKDIR /app

# Volta para o usuário padrão
USER 1001

CMD ["/init-git.sh"]
